// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Singula.Core.Infrastructure.Data;

#nullable disable

namespace Singula.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReporteDetalle", b =>
                {
                    b.Property<int>("IdReporte")
                        .HasColumnType("integer")
                        .HasColumnName("id_reporte");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitud");

                    b.HasKey("IdReporte", "IdSolicitud")
                        .HasName("reporte_detalle_pkey");

                    b.HasIndex(new[] { "IdSolicitud" }, "ix_repdet_solicitud");

                    b.ToTable("reporte_detalle", (string)null);
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.Property<int>("IdRolSistema")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol_sistema");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer")
                        .HasColumnName("id_permiso");

                    b.HasKey("IdRolSistema", "IdPermiso")
                        .HasName("rol_permiso_pkey");

                    b.HasIndex(new[] { "IdPermiso" }, "ix_rol_permiso_perm");

                    b.ToTable("rol_permiso", (string)null);
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Alertum", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_alerta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAlerta"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<bool?>("EnviadoEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("enviado_email");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_lectura");

                    b.Property<int>("IdEstadoAlerta")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_alerta");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitud");

                    b.Property<int>("IdTipoAlerta")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_alerta");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<string>("Nivel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nivel");

                    b.HasKey("IdAlerta")
                        .HasName("alerta_pkey");

                    b.HasIndex(new[] { "IdEstadoAlerta" }, "ix_alerta_estado");

                    b.HasIndex(new[] { "IdSolicitud" }, "ix_alerta_solicitud");

                    b.HasIndex(new[] { "IdTipoAlerta" }, "ix_alerta_tipo");

                    b.ToTable("alerta");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Area", b =>
                {
                    b.Property<int>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_area");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArea"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreArea")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre_area");

                    b.HasKey("IdArea")
                        .HasName("area_pkey");

                    b.HasIndex(new[] { "NombreArea" }, "area_nombre_area_key")
                        .IsUnique();

                    b.ToTable("area");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.ConfigSla", b =>
                {
                    b.Property<int>("IdSla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_sla");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSla"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("actualizado_por");

                    b.Property<string>("CodigoSla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_sla");

                    b.Property<DateTime?>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("DiasUmbral")
                        .HasColumnType("integer")
                        .HasColumnName("dias_umbral");

                    b.Property<bool?>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<int>("IdTipoSolicitud")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_solicitud");

                    b.HasKey("IdSla")
                        .HasName("config_sla_pkey");

                    b.HasIndex("ActualizadoPor");

                    b.HasIndex("CreadoPor");

                    b.HasIndex(new[] { "CodigoSla" }, "config_sla_codigo_sla_key")
                        .IsUnique();

                    b.HasIndex(new[] { "EsActivo" }, "ix_config_sla_activo");

                    b.HasIndex(new[] { "IdTipoSolicitud" }, "ix_config_sla_tipo");

                    b.ToTable("config_sla");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.EstadoAlertaCatalogo", b =>
                {
                    b.Property<int>("IdEstadoAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_alerta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoAlerta"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdEstadoAlerta")
                        .HasName("estado_alerta_catalogo_pkey");

                    b.HasIndex(new[] { "Codigo" }, "estado_alerta_catalogo_codigo_key")
                        .IsUnique();

                    b.ToTable("estado_alerta_catalogo");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.EstadoSolicitudCatalogo", b =>
                {
                    b.Property<int>("IdEstadoSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_solicitud");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoSolicitud"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdEstadoSolicitud")
                        .HasName("estado_solicitud_catalogo_pkey");

                    b.HasIndex(new[] { "Codigo" }, "estado_solicitud_catalogo_codigo_key")
                        .IsUnique();

                    b.ToTable("estado_solicitud_catalogo");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.EstadoUsuarioCatalogo", b =>
                {
                    b.Property<int>("IdEstadoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoUsuario"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdEstadoUsuario")
                        .HasName("estado_usuario_catalogo_pkey");

                    b.HasIndex(new[] { "Codigo" }, "estado_usuario_catalogo_codigo_key")
                        .IsUnique();

                    b.ToTable("estado_usuario_catalogo");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_permiso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.HasKey("IdPermiso")
                        .HasName("permiso_pkey");

                    b.HasIndex(new[] { "Codigo" }, "permiso_codigo_key")
                        .IsUnique();

                    b.ToTable("permiso");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Personal", b =>
                {
                    b.Property<int>("IdPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_personal");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPersonal"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("apellidos");

                    b.Property<DateTime?>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombres")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombres");

                    b.HasKey("IdPersonal")
                        .HasName("personal_pkey");

                    b.HasIndex(new[] { "Documento" }, "ix_personal_documento");

                    b.HasIndex(new[] { "Estado" }, "ix_personal_estado");

                    b.HasIndex(new[] { "IdUsuario" }, "personal_id_usuario_key")
                        .IsUnique();

                    b.ToTable("personal");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.PrioridadCatalogo", b =>
                {
                    b.Property<int>("IdPrioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_prioridad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrioridad"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<decimal>("SlaMultiplier")
                        .HasColumnType("numeric")
                        .HasColumnName("sla_multiplier");

                    b.HasKey("IdPrioridad")
                        .HasName("prioridad_catalogo_pkey");

                    b.ToTable("prioridad_catalogo");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_reporte");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReporte"));

                    b.Property<DateTime?>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generacion")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FiltrosJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("filtros_json");

                    b.Property<string>("Formato")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("formato");

                    b.Property<int>("GeneradoPor")
                        .HasColumnType("integer")
                        .HasColumnName("generado_por");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("ruta_archivo");

                    b.Property<string>("TipoReporte")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo_reporte");

                    b.HasKey("IdReporte")
                        .HasName("reporte_pkey");

                    b.HasIndex(new[] { "FiltrosJson" }, "ix_reporte_filtros_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "FiltrosJson" }, "ix_reporte_filtros_gin"), "gin");

                    b.HasIndex(new[] { "GeneradoPor", "FechaGeneracion" }, "ix_reporte_generado")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "TipoReporte", "Formato" }, "ix_reporte_tipo_formato");

                    b.ToTable("reporte");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.RolRegistro", b =>
                {
                    b.Property<int>("IdRolRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol_registro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRolRegistro"));

                    b.Property<string>("BloqueTech")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("bloque_tech");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRolRegistro")
                        .HasName("rol_registro_pkey");

                    b.HasIndex(new[] { "NombreRol" }, "rol_registro_nombre_rol_key")
                        .IsUnique();

                    b.ToTable("rol_registro");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.RolesSistema", b =>
                {
                    b.Property<int>("IdRolSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol_sistema");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRolSistema"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("es_activo");

                    b.Property<string>("Nombre")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRolSistema")
                        .HasName("roles_sistema_pkey");

                    b.HasIndex(new[] { "Codigo" }, "roles_sistema_codigo_key")
                        .IsUnique();

                    b.ToTable("roles_sistema");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitud");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSolicitud"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<int?>("ActualizadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("actualizado_por");

                    b.Property<DateTime?>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("creado_por");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateTime?>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_solicitud");

                    b.Property<int>("IdArea")
                        .HasColumnType("integer")
                        .HasColumnName("id_area");

                    b.Property<int>("IdEstadoSolicitud")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_solicitud");

                    b.Property<int>("IdPersonal")
                        .HasColumnType("integer")
                        .HasColumnName("id_personal");

                    b.Property<int>("IdRolRegistro")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol_registro");

                    b.Property<int>("IdSla")
                        .HasColumnType("integer")
                        .HasColumnName("id_sla");

                    b.Property<int?>("NumDiasSla")
                        .HasColumnType("integer")
                        .HasColumnName("num_dias_sla");

                    b.Property<string>("OrigenDato")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("origen_dato");

                    b.Property<string>("Prioridad")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prioridad");

                    b.Property<string>("ResumenSla")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("resumen_sla");

                    b.HasKey("IdSolicitud")
                        .HasName("solicitud_pkey");

                    b.HasIndex("ActualizadoPor");

                    b.HasIndex(new[] { "IdArea" }, "ix_solicitud_area");

                    b.HasIndex(new[] { "CreadoPor" }, "ix_solicitud_creado_por");

                    b.HasIndex(new[] { "IdEstadoSolicitud" }, "ix_solicitud_estado");

                    b.HasIndex(new[] { "FechaSolicitud", "FechaIngreso" }, "ix_solicitud_fechas");

                    b.HasIndex(new[] { "IdPersonal" }, "ix_solicitud_personal");

                    b.HasIndex(new[] { "IdRolRegistro" }, "ix_solicitud_rol_registro");

                    b.HasIndex(new[] { "IdSla" }, "ix_solicitud_sla");

                    b.ToTable("solicitud");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.TipoAlertaCatalogo", b =>
                {
                    b.Property<int>("IdTipoAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_alerta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoAlerta"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdTipoAlerta")
                        .HasName("tipo_alerta_catalogo_pkey");

                    b.HasIndex(new[] { "Codigo" }, "tipo_alerta_catalogo_codigo_key")
                        .IsUnique();

                    b.ToTable("tipo_alerta_catalogo");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.TipoSolicitudCatalogo", b =>
                {
                    b.Property<int>("IdTipoSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_solicitud");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoSolicitud"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdTipoSolicitud")
                        .HasName("tipo_solicitud_catalogo_pkey");

                    b.HasIndex(new[] { "Codigo" }, "tipo_solicitud_catalogo_codigo_key")
                        .IsUnique();

                    b.ToTable("tipo_solicitud_catalogo");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(190)
                        .HasColumnType("character varying(190)")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("IdEstadoUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado_usuario");

                    b.Property<int>("IdRolSistema")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol_sistema");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_login");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario")
                        .HasName("usuario_pkey");

                    b.HasIndex(new[] { "IdEstadoUsuario" }, "ix_usuario_estado");

                    b.HasIndex(new[] { "IdRolSistema" }, "ix_usuario_rol");

                    b.HasIndex(new[] { "Correo" }, "usuario_correo_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "usuario_username_key")
                        .IsUnique();

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("ReporteDetalle", b =>
                {
                    b.HasOne("Singula.Core.Core.Entities.Reporte", null)
                        .WithMany()
                        .HasForeignKey("IdReporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reporte_detalle_id_reporte_fkey");

                    b.HasOne("Singula.Core.Core.Entities.Solicitud", null)
                        .WithMany()
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reporte_detalle_id_solicitud_fkey");
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.HasOne("Singula.Core.Core.Entities.Permiso", null)
                        .WithMany()
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("rol_permiso_id_permiso_fkey");

                    b.HasOne("Singula.Core.Core.Entities.RolesSistema", null)
                        .WithMany()
                        .HasForeignKey("IdRolSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("rol_permiso_id_rol_sistema_fkey");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Alertum", b =>
                {
                    b.HasOne("Singula.Core.Core.Entities.EstadoAlertaCatalogo", "IdEstadoAlertaNavigation")
                        .WithMany("Alerta")
                        .HasForeignKey("IdEstadoAlerta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("alerta_id_estado_alerta_fkey");

                    b.HasOne("Singula.Core.Core.Entities.Solicitud", "IdSolicitudNavigation")
                        .WithMany("Alerta")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("alerta_id_solicitud_fkey");

                    b.HasOne("Singula.Core.Core.Entities.TipoAlertaCatalogo", "IdTipoAlertaNavigation")
                        .WithMany("Alerta")
                        .HasForeignKey("IdTipoAlerta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("alerta_id_tipo_alerta_fkey");

                    b.Navigation("IdEstadoAlertaNavigation");

                    b.Navigation("IdSolicitudNavigation");

                    b.Navigation("IdTipoAlertaNavigation");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.ConfigSla", b =>
                {
                    b.HasOne("Singula.Core.Core.Entities.Usuario", "ActualizadoPorNavigation")
                        .WithMany("ConfigSlaActualizadoPorNavigations")
                        .HasForeignKey("ActualizadoPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("config_sla_actualizado_por_fkey");

                    b.HasOne("Singula.Core.Core.Entities.Usuario", "CreadoPorNavigation")
                        .WithMany("ConfigSlaCreadoPorNavigations")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("config_sla_creado_por_fkey");

                    b.HasOne("Singula.Core.Core.Entities.TipoSolicitudCatalogo", "IdTipoSolicitudNavigation")
                        .WithMany("ConfigSlas")
                        .HasForeignKey("IdTipoSolicitud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("config_sla_id_tipo_solicitud_fkey");

                    b.Navigation("ActualizadoPorNavigation");

                    b.Navigation("CreadoPorNavigation");

                    b.Navigation("IdTipoSolicitudNavigation");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Personal", b =>
                {
                    b.HasOne("Singula.Core.Core.Entities.Usuario", "IdUsuarioNavigation")
                        .WithOne("Personal")
                        .HasForeignKey("Singula.Core.Core.Entities.Personal", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("personal_id_usuario_fkey");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Reporte", b =>
                {
                    b.HasOne("Singula.Core.Core.Entities.Usuario", "GeneradoPorNavigation")
                        .WithMany("Reportes")
                        .HasForeignKey("GeneradoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("reporte_generado_por_fkey");

                    b.Navigation("GeneradoPorNavigation");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Solicitud", b =>
                {
                    b.HasOne("Singula.Core.Core.Entities.Usuario", "ActualizadoPorNavigation")
                        .WithMany("SolicitudActualizadoPorNavigations")
                        .HasForeignKey("ActualizadoPor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("solicitud_actualizado_por_fkey");

                    b.HasOne("Singula.Core.Core.Entities.Usuario", "CreadoPorNavigation")
                        .WithMany("SolicitudCreadoPorNavigations")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("solicitud_creado_por_fkey");

                    b.HasOne("Singula.Core.Core.Entities.Area", "IdAreaNavigation")
                        .WithMany("Solicituds")
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("solicitud_id_area_fkey");

                    b.HasOne("Singula.Core.Core.Entities.EstadoSolicitudCatalogo", "IdEstadoSolicitudNavigation")
                        .WithMany("Solicituds")
                        .HasForeignKey("IdEstadoSolicitud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("solicitud_id_estado_solicitud_fkey");

                    b.HasOne("Singula.Core.Core.Entities.Personal", "IdPersonalNavigation")
                        .WithMany("Solicituds")
                        .HasForeignKey("IdPersonal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("solicitud_id_personal_fkey");

                    b.HasOne("Singula.Core.Core.Entities.RolRegistro", "IdRolRegistroNavigation")
                        .WithMany("Solicituds")
                        .HasForeignKey("IdRolRegistro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("solicitud_id_rol_registro_fkey");

                    b.HasOne("Singula.Core.Core.Entities.ConfigSla", "IdSlaNavigation")
                        .WithMany("Solicituds")
                        .HasForeignKey("IdSla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("solicitud_id_sla_fkey");

                    b.Navigation("ActualizadoPorNavigation");

                    b.Navigation("CreadoPorNavigation");

                    b.Navigation("IdAreaNavigation");

                    b.Navigation("IdEstadoSolicitudNavigation");

                    b.Navigation("IdPersonalNavigation");

                    b.Navigation("IdRolRegistroNavigation");

                    b.Navigation("IdSlaNavigation");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Usuario", b =>
                {
                    b.HasOne("Singula.Core.Core.Entities.EstadoUsuarioCatalogo", "IdEstadoUsuarioNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEstadoUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("usuario_id_estado_usuario_fkey");

                    b.HasOne("Singula.Core.Core.Entities.RolesSistema", "IdRolSistemaNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRolSistema")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("usuario_id_rol_sistema_fkey");

                    b.Navigation("IdEstadoUsuarioNavigation");

                    b.Navigation("IdRolSistemaNavigation");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Area", b =>
                {
                    b.Navigation("Solicituds");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.ConfigSla", b =>
                {
                    b.Navigation("Solicituds");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.EstadoAlertaCatalogo", b =>
                {
                    b.Navigation("Alerta");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.EstadoSolicitudCatalogo", b =>
                {
                    b.Navigation("Solicituds");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.EstadoUsuarioCatalogo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Personal", b =>
                {
                    b.Navigation("Solicituds");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.RolRegistro", b =>
                {
                    b.Navigation("Solicituds");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.RolesSistema", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Solicitud", b =>
                {
                    b.Navigation("Alerta");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.TipoAlertaCatalogo", b =>
                {
                    b.Navigation("Alerta");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.TipoSolicitudCatalogo", b =>
                {
                    b.Navigation("ConfigSlas");
                });

            modelBuilder.Entity("Singula.Core.Core.Entities.Usuario", b =>
                {
                    b.Navigation("ConfigSlaActualizadoPorNavigations");

                    b.Navigation("ConfigSlaCreadoPorNavigations");

                    b.Navigation("Personal");

                    b.Navigation("Reportes");

                    b.Navigation("SolicitudActualizadoPorNavigations");

                    b.Navigation("SolicitudCreadoPorNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
